### ISSUE TITLE
Definir o dono do plano de ação

### ISSUE THREAD

**Issue by orafa** [orafa/Melhoria-dos-resultados-2016#12]

**Comment by juliocezar** [comment]
Meta de MRR Q1:
Jan = 20k
Fev = 40k
Mar = 40k
Total = 100k
Realizado = 84k

Estamos com 84% da meta de MRR atingida no Q1 isso juntando base + novas receitas com todos os times de venda (Inbound, Inside e Field Sales), á tendência que ainda tenha alterações nos números até semana que vem.

Meta de faturamento Q1 em novas receitas é de 180k, Bahuan, pode nos passar o que foi faturado de novas receitas, até o momento? 

Pessoal conversando com o Miagui á tendência é que á meta comercial seja somente baseada em MRR, depois temos que discutir como ficará essa KPI  de faturamento, caso seja feita essa mudanca, ok?

Plano de ação comercial Q1 e Q2:
Q1:
- Trabalhar nas contas que estão com o ciclo de vendas no limite do legado de 2015 para acontecer ainda no Q1.Já aconteceu.

- Aplicação das metodologias Sell More para aceleração de vendas de Deals 2016.

- (Semana  passada) Pipeline Quente Março:  60k em jogo quentes. Desses, expectativa alta de fechar 35k em março. Com esse resultado a meta de Março é alcançada e no geral, ficaremos cerca de 70% da meta do Trimestre de MRR (meta de 100k de MRR - contando todas as áreas - comercial e base. Trouxemos 61k somente essa semana.

- (Essa e próxima semana, última de março) Temos Forescast de 91k juntando todos os times de vendas, expectativa que a gente traga os 16k restante para bater á meta de MRR no Q1.

Q2:
- Entrada de novos produtos como Kast, Samba Content, Plugin WordPress e Samba Vídeos Cacheado que ajudará no aumento de ticket.
- Ciclo de vendas chegando ao fim para as contas que foram geradas no Q1
- Reduzir ciclo de vendas e aumentar ticket (sellmore pode nos ajudar aqui também)
- Tempo de experiêcia da nova equipe já vence em abril, então no q2, já esperamos todos performando
- Como uma visão geral, certamente, vamos bater a meta de março de MRR.
