### ISSUE TITLE
Alinhar com o Everton papel do novo Analista Comercial em SP para CS

### ISSUE THREAD

**Issue by orafa** [orafa/Melhoria-dos-resultados-2016#5]

**Comment by mottoca** [comment]
"A ideia é ter um CS senior em SP para ajudar o time de BH, hoje essa demanda acaba sendo feita por mim. Ele vai cuidar das grandes contas com as funções descritas na vaga divulgada."

Mais algum comentario @lilianoliveiracf ? OU podemos fechar essa issue? Esse analista vai atender o que você esperava?

**Comment by lilianoliveiracf** [comment]
Atende sim no sentido de auxiliar o Everton. Só vamos alinhar com ele a estratégia de CS e dos top 10.
