### ISSUE TITLE
Desenvolver treinamentos técnicos

### ISSUE THREAD

**Issue by orafa** [orafa/Melhoria-dos-resultados-2016#8]

**Comment by ramonsouza** [comment]
Já temos treinamentos técnicos criados para o : 
- Samba Videos
- Samba Live
- Samba Class

Provas de certificação criadas e disparadas pelo RH, tanto do Samba Videos quanto do Samba Class.

Também temos um treinamento de melhores práticas, exemplificando cases dos nossos clientes e informações que auxiliam na conversação e vendas para prospects.
